HEADERS += \
    $$PWD/httprequestservice.h \
    $$PWD/gbssession.h \
    $$PWD/servicemanager.h \
    $$PWD/serviceinterface.h \
    $$PWD/base/department/editdeparment.h \
    $$PWD/base/department/querydepartment.h \
    $$PWD/base/permission/editpersission.h \
    $$PWD/base/permission/querypermission.h \
    $$PWD/base/role/editrole.h \
    $$PWD/base/role/queryroletable.h \
    $$PWD/base/user/edituser.h \
    $$PWD/base/user/queryuser.h \
    $$PWD/base/vehicletype/editvehicletype.h \
    $$PWD/base/vehicletype/queryvehicletype.h \
    $$PWD/base/vehicle/editvehicle.h \
    $$PWD/base/vehicle/queryvehicle.h \
    $$PWD/base/warehouse/editwarehouse.h \
    $$PWD/base/warehouse/querywarehouse.h \
    $$PWD/base/banktype/editbanktype.h \
    $$PWD/base/banktype/querybanktype.h \
    $$PWD/base/seller/editseller.h \
    $$PWD/base/seller/queryseller.h \
    $$PWD/base/supplier/editsupplier.h \
    $$PWD/base/supplier/querysupplier.h \
    $$PWD/base/transport/edittransport.h \
    $$PWD/base/transport/querytransport.h \
    $$PWD/base/paymenttype/editpaymenttype.h \
    $$PWD/base/paymenttype/querypaymenttype.h \
    $$PWD/base/packtype/editpacktype.h \
    $$PWD/base/packtype/querypacktype.h \
    $$PWD/base/graintype/editgraintype.h \
    $$PWD/base/graintype/querygraintype.h \
    $$PWD/base/sampleclass/editsampleclass.h \
    $$PWD/base/sampleclass/querysampleclass.h \
    $$PWD/base/contracttype/editcontracttype.h \
    $$PWD/base/contracttype/querycontracttype.h \
    $$PWD/base/procedurenode/editprocedurenode.h \
    $$PWD/base/procedurenode/queryprocedurenode.h \
    $$PWD/base/purchase/editpurchase.h \
    $$PWD/base/purchase/querypurchase.h \
    $$PWD/base/valuation/editvaluation.h \
    $$PWD/base/valuation/queryvaluation.h \
    $$PWD/base/contract/editcontract.h \
    $$PWD/base/contract/querycontract.h \
    $$PWD/business/register/editregister.h \
    $$PWD/business/register/queryregister.h \
    $$PWD/business/queryseller/queryseller.h \
    $$PWD/business/querypicture/querypicture.h \
    $$PWD/business/queryseller/querysellerbyidentityid.h \
    $$PWD/business/queryRegistbyTagNum/queryregisterbytagnum.h \
    $$PWD/business/sampling/editsampling.h \
    $$PWD/business/sampling/querysampling.h \
    $$PWD/business/queryassaybySampleBox/queryassaybysamplebox.h \
    $$PWD/business/assay/editassay.h \
    $$PWD/business/assay/queryassay.h \
    $$PWD/business/queryassaytosell/queryassaytosell.h \
    $$PWD/business/sell/editsell.h \
    $$PWD/business/sell/querysell.h \
    $$PWD/business/sell/sellgrain.h \
    $$PWD/business/weigh/editweigh.h \
    $$PWD/business/weigh/queryweigh.h \
    $$PWD/business/querypicture/queryweighpicture.h \
    $$PWD/business/weigh/alterweigh.h \
    $$PWD/business/unload/editunload.h \
    $$PWD/business/unload/queryunload.h \
    $$PWD/business/queryRegisterbylicense/queryregisterbylicense.h


SOURCES += \
    $$PWD/httprequestservice.cpp \
    $$PWD/gbssession.cpp \
    $$PWD/servicemanager.cpp \
    $$PWD/base/department/editdeparment.cpp \
    $$PWD/base/department/querydepartment.cpp \
    $$PWD/base/permission/editpersission.cpp \
    $$PWD/base/permission/querypermission.cpp \
    $$PWD/base/role/editrole.cpp \
    $$PWD/base/role/queryroletable.cpp \
    $$PWD/base/user/edituser.cpp \
    $$PWD/base/user/queryuser.cpp \
    $$PWD/base/vehicletype/editvehicletype.cpp \
    $$PWD/base/vehicletype/queryvehicletype.cpp \
    $$PWD/base/vehicle/editvehicle.cpp \
    $$PWD/base/vehicle/queryvehicle.cpp \
    $$PWD/base/warehouse/editwarehouse.cpp \
    $$PWD/base/warehouse/querywarehouse.cpp \
    $$PWD/base/banktype/editbanktype.cpp \
    $$PWD/base/banktype/querybanktype.cpp \
    $$PWD/base/seller/editseller.cpp \
    $$PWD/base/seller/queryseller.cpp \
    $$PWD/base/supplier/editsupplier.cpp \
    $$PWD/base/supplier/querysupplier.cpp \
    $$PWD/base/transport/edittransport.cpp \
    $$PWD/base/transport/querytransport.cpp \
    $$PWD/base/paymenttype/editpaymenttype.cpp \
    $$PWD/base/paymenttype/querypaymenttype.cpp \
    $$PWD/base/packtype/editpacktype.cpp \
    $$PWD/base/packtype/querypacktype.cpp \
    $$PWD/base/graintype/editgraintype.cpp \
    $$PWD/base/graintype/querygraintype.cpp \
    $$PWD/base/sampleclass/editsampleclass.cpp \
    $$PWD/base/sampleclass/querysampleclass.cpp \
    $$PWD/base/contracttype/editcontracttype.cpp \
    $$PWD/base/contracttype/querycontracttype.cpp \
    $$PWD/base/procedurenode/ediprocedurenode.cpp \
    $$PWD/base/procedurenode/queryprocedurenode.cpp \
    $$PWD/base/purchase/editpurchase.cpp \
    $$PWD/base/purchase/querypurchase.cpp \
    $$PWD/base/valuation/editvaluation.cpp \
    $$PWD/base/valuation/queryvaluation.cpp \
    $$PWD/base/contract/editcontract.cpp \
    $$PWD/base/contract/querycontract.cpp \
    $$PWD/business/register/editregister.cpp \
    $$PWD/business/register/queryregister.cpp \
    $$PWD/business/queryseller/querysellerbyidentityid.cpp \
    $$PWD/business/querypicture/querypicture.cpp \
    $$PWD/business/queryRegistbyTagNum/queryregisterbytagnum.cpp \
    $$PWD/business/sampling/editsampling.cpp \
    $$PWD/business/sampling/querysampling.cpp \
    $$PWD/business/queryassaybySampleBox/queryassaybysamplebox.cpp \
    $$PWD/business/queryRegisterbylicense/queryregisterbylicense.cpp\
    $$PWD/business/querypicture/queryweighpicture.cpp \
    $$PWD/business/assay/editassay.cpp \
    $$PWD/business/assay/queryassay.cpp \
    $$PWD/business/queryassaytosell/queryassaytosell.cpp \
    $$PWD/business/sell/querysell.cpp \
    $$PWD/business/sell/sellgrain.cpp \
    $$PWD/business/weigh/editweigh.cpp \
    $$PWD/business/weigh/queryweigh.cpp \
    $$PWD/business/weigh/alterweigh.cpp \
    $$PWD/business/unload/editunload.cpp \
    $$PWD/business/unload/queryunload.cpp \
