FORMS += \
    $$PWD/frmrole/frmroleedit.ui \
    $$PWD/frmrole/frmroletable.ui\
    $$PWD/frmpermission/frmpermissionedit.ui \
    $$PWD/frmpermission/frmpermissiontable.ui\
    $$PWD/frmdepartment/frmdepartmentedit.ui \
    $$PWD/frmdepartment/frmdepartmenttable.ui \
    $$PWD/frmuser/frmuseredit.ui \
    $$PWD/frmuser/frmusertable.ui \
    $$PWD/frmvehicletype/frmvehicletypeedit.ui \
    $$PWD/frmvehicletype/frmvehicletypetable.ui \
    $$PWD/frmvehicle/frmvehicleedit.ui \
    $$PWD/frmvehicle/frmvehicletable.ui \
    $$PWD/frmwarehouse/frmwarehouseedit.ui \
    $$PWD/frmwarehouse/frmwarehousetable.ui \
    $$PWD/frmbanktype/frmbanktypeedit.ui \
    $$PWD/frmbanktype/frmbanktypetable.ui \
    $$PWD/frmseller/frmselleredit.ui \
    $$PWD/frmseller/frmsellertable.ui \
    $$PWD/frmsupplier/frmsupplieredit.ui \
    $$PWD/frmsupplier/frmsuppliertable.ui \
    $$PWD/frmtransport/frmtransportedit.ui \
    $$PWD/frmtransport/frmtransporttable.ui \
    $$PWD/frmpaymenttype/frmpaymenttypeedit.ui \
    $$PWD/frmpaymenttype/frmpaymenttypetable.ui \
    $$PWD/frmpacktype/frmpacktypeedit.ui \
    $$PWD/frmpacktype/frmpacktypetable.ui \
    $$PWD/frmgraintype/frmgraintypeedit.ui \
    $$PWD/frmgraintype/frmgraintypetable.ui \
    $$PWD/frmsampleclass/frmsampleclassedit.ui \
    $$PWD/frmsampleclass/frmsampleclasstable.ui \
    $$PWD/frmcontracttype/frmcontracttypeedit.ui \
    $$PWD/frmcontracttype/frmcontracttypetable.ui \
    $$PWD/frmprocedurenode/frmprocedurenodeedit.ui \
    $$PWD/frmprocedurenode/frmprocedurenodetable.ui \
    $$PWD/frmpurchase/frmpurchaseedit.ui \
    $$PWD/frmpurchase/frmpurchasetable.ui \
    $$PWD/frmvaluation/frmvaluationedit.ui \
    $$PWD/frmvaluation/frmvaluationtable.ui \
    $$PWD/frmvaluation/frmvaluationlist.ui \
    $$PWD/frmvaluation/frmrule.ui \
    $$PWD/frmcontract/frmcontractedit.ui \
    $$PWD/frmcontract/frmcontracttable.ui \
    $$PWD/frmregister/frmregistertable.ui \
    $$PWD/frmregister/frmregisteredit.ui \
    $$PWD/frmsampling/frmsamplingedit.ui \
    $$PWD/frmsampling/frmsamplingtable.ui \
    $$PWD/frmassay/frmassayedit.ui \
    $$PWD/frmassay/frmassaytable.ui \
    $$PWD/frmsell/frmselledit.ui \
    $$PWD/frmsell/frmselltable.ui \
    $$PWD/frmweigh/frmweighedit.ui \
    $$PWD/frmweigh/frmweightable.ui



HEADERS += \
    $$PWD/frmrole/frmroleedit.h \
    $$PWD/frmrole/frmroletable.h\
    $$PWD/frmpermission/frmpermissionedit.h \
    $$PWD/frmpermission/frmpermissiontable.h\
    $$PWD/frmtablebase.h \
    $$PWD/frmdepartment/frmdepartmentedit.h \
    $$PWD/frmdepartment/frmdepartmenttable.h \
    $$PWD/frmuser/frmuseredit.h \
    $$PWD/frmuser/frmusertable.h \
    $$PWD/frmvehicletype/frmvehicletypeedit.h \
    $$PWD/frmvehicletype/frmvehicletypetable.h \
    $$PWD/frmvehicle/frmvehicleedit.h \
    $$PWD/frmvehicle/frmvehicletable.h \
    $$PWD/frmwarehouse/frmwarehouseedit.h \
    $$PWD/frmwarehouse/frmwarehousetable.h \
    $$PWD/frmbanktype/frmbanktypeedit.h \
    $$PWD/frmbanktype/frmbanktypetable.h \
    $$PWD/frmseller/frmselleredit.h \
    $$PWD/frmseller/frmsellertable.h \
    $$PWD/frmsupplier/frmsupplieredit.h \
    $$PWD/frmsupplier/frmsuppliertable.h \
    $$PWD/frmtransport/frmtransportedit.h \
    $$PWD/frmtransport/frmtransporttable.h \
    $$PWD/frmpaymenttype/frmpaymenttypeedit.h \
    $$PWD/frmpaymenttype/frmpaymenttypetable.h \
    $$PWD/frmpacktype/frmpacktypeedit.h \
    $$PWD/frmpacktype/frmpacktypetable.h \
    $$PWD/frmgraintype/frmgraintypeedit.h \
    $$PWD/frmgraintype/frmgraintypetable.h \
    $$PWD/frmsampleclass/frmsampleclassedit.h \
    $$PWD/frmsampleclass/frmsampleclasstable.h \
    $$PWD/frmcontracttype/frmcontracttypeedit.h \
    $$PWD/frmcontracttype/frmcontracttypetable.h \
    $$PWD/frmprocedurenode/frmprocedurenodeedit.h \
    $$PWD/frmprocedurenode/frmprocedurenodetable.h \
    $$PWD/frmpurchase/frmpurchaseedit.h \
    $$PWD/frmpurchase/frmpurchasetable.h \
    $$PWD/frmvaluation/frmvaluationedit.h \
    $$PWD/frmvaluation/frmvaluationtable.h \
    $$PWD/frmvaluation/frmvaluationlist.h \
    $$PWD/frmvaluation/frmrule.h \
    $$PWD/frmcontract/frmcontractedit.h \
    $$PWD/frmcontract/frmcontracttable.h \
    $$PWD/frmregister/frmregistertable.h \
    $$PWD/frmregister/frmregisteredit.h \
    $$PWD/frmsampling/frmsamplingedit.h \
    $$PWD/frmsampling/frmsamplingtable.h \
    $$PWD/frmassay/frmassayedit.h \
    $$PWD/frmassay/frmassaytable.h \
    $$PWD/frmsell/frmselledit.h \
    $$PWD/frmsell/frmselltable.h \
    $$PWD/frmweigh/frmweighedit.h \
    $$PWD/frmweigh/frmweightable.h

SOURCES += \
    $$PWD/frmpermission/frmpermissionedit.cpp \
    $$PWD/frmpermission/frmpermissiontable.cpp\
    $$PWD/frmtablebase.cpp \
    $$PWD/frmrole/frmroleedit.cpp \
    $$PWD/frmrole/frmroletable.cpp \
    $$PWD/frmdepartment/frmdepartmentedit.cpp \
    $$PWD/frmdepartment/frmdepartmenttable.cpp \
    $$PWD/frmuser/frmuseredit.cpp \
    $$PWD/frmuser/frmusertable.cpp \
    $$PWD/frmvehicletype/frmvehicletypeedit.cpp \
    $$PWD/frmvehicletype/frmvehicletypetable.cpp \
    $$PWD/frmvehicle/frmvehicleedit.cpp \
    $$PWD/frmvehicle/frmvehicletable.cpp \
    $$PWD/frmwarehouse/frmwarehouseedit.cpp \
    $$PWD/frmwarehouse/frmwarehousetable.cpp \
    $$PWD/frmbanktype/frmbanktypeedit.cpp \
    $$PWD/frmbanktype/frmbanktypetable.cpp \
    $$PWD/frmseller/frmselleredit.cpp \
    $$PWD/frmseller/frmsellertable.cpp \
    $$PWD/frmsupplier/frmsupplieredit.cpp \
    $$PWD/frmsupplier/frmsuppliertable.cpp \
    $$PWD/frmtransport/frmtransport.cpp \
    $$PWD/frmtransport/frmtransporttable.cpp \
    $$PWD/frmpaymenttype/frmpaymenttypeedit.cpp \
    $$PWD/frmpaymenttype/frmpaymenttypetable.cpp \
    $$PWD/frmpacktype/frmpacktypeedit.cpp \
    $$PWD/frmpacktype/frmpacktypetable.cpp \
    $$PWD/frmgraintype/frmgraintypeedit.cpp \
    $$PWD/frmgraintype/frmgraintypetable.cpp \
    $$PWD/frmsampleclass/frmsampleclassedit.cpp \
    $$PWD/frmsampleclass/frmsampleclasstable.cpp \
    $$PWD/frmcontracttype/frmcontracttypeedit.cpp \
    $$PWD/frmcontracttype/frmcontracttypetable.cpp \
    $$PWD/frmprocedurenode/frmprocedurenodeedit.cpp \
    $$PWD/frmprocedurenode/frmprocedurenodetable.cpp \
    $$PWD/frmpurchase/frmpurchaseedit.cpp \
    $$PWD/frmpurchase/frmpurchasetable.cpp \
    $$PWD/frmvaluation/frmvaluationedit.cpp \
    $$PWD/frmvaluation/frmvaluationtable.cpp \
    $$PWD/frmvaluation/frmvaluationlist.cpp \
    $$PWD/frmvaluation/frmrule.cpp \
    $$PWD/frmcontract/frmcontractedit.cpp \
    $$PWD/frmcontract/frmcontracttable.cpp \
    $$PWD/frmregister/frmregistertable.cpp \
    $$PWD/frmregister/frmregisteredit.cpp \
    $$PWD/frmsampling/frmsamplingedit.cpp \
    $$PWD/frmsampling/frmsamplingtable.cpp \
    $$PWD/frmassay/frmassayedit.cpp \
    $$PWD/frmassay/frmassaytable.cpp \
    $$PWD/frmsell/frmselledit.cpp \
    $$PWD/frmsell/frmselltable.cpp \
    $$PWD/frmweigh/frmweighedit.cpp \
    $$PWD/frmweigh/frmweightable.cpp
